name: ML_selection_ENV
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.24
  - pandas>=2.0
  - scikit-learn>=1.3
  - matplotlib>=3.7
  - seaborn>=0.12
  - jupyter>=1.0
  - notebook>=6.5
  - ipywidgets>=8.0
  - plotly>=5.0
  - pip
  - pip:
    - imbalanced-learn>=0.11
    - xgboost>=1.7
    - lightgbm>=4.0
    - catboost>=1.2
    - optuna>=3.3
    - shap>=0.42
